# XOR Binary Classification

 Xor Logical Operator | Neural Network
:-:|:-:
![x_and_y](img/xor_operator.png) | ![x_and_y](img/neural_network.png)

# 0 - IMPORTS

In [19]:
import tensorflow as tf
import numpy as np
import warnings


warnings.filterwarnings('ignore')

# 1 - CREATE X, y VARIABLES

In [10]:
X = np.array([[0,0], [0,1], [1,0], [1,1]])
print('X Values\n', X, '\n')

y = np.array([[0], [1], [1], [0]])
print('y Values\n', y)

X Values
 [[0 0]
 [0 1]
 [1 0]
 [1 1]] 

y Values
 [[0]
 [1]
 [1]
 [0]]


# 2 - NEURAL NETWORK STRUCTURE

In [11]:
input_layer  = 2
hidden_layer = 3
output_layer = 1

# 3 - CREATE WEIGHT LAYERS VARIABLES

In [12]:
W = {'hidden': tf.Variable(tf.random_normal([input_layer, hidden_layer]), name = 'w_hidden'),  # weight hidden layer
     'output': tf.Variable(tf.random_normal([hidden_layer, output_layer]), name = 'w_output')} # weight output layer

# 4 - CREATE BIAS LAYERS VARIABLES

In [16]:
b = {'hidden': tf.Variable(tf.random_normal([hidden_layer]), name = 'b_hidden'),
     'output': tf.Variable(tf.random_normal([output_layer]), name = 'b_output')}

# 5 - CREATE PLACEHOLDERS

In [17]:
irows = 4
xph = tf.placeholder(tf.float32, [irows, input_layer], name = 'xph')
yph = tf.placeholder(tf.float32, [irows, output_layer], name = 'yph')

# 6 - CREATE NEURAL NETWORKS TENSORS

In [20]:
# input layer to hidden layer operations
hidden_layer_calc       = tf.add(tf.matmul(xph, W['hidden']), b['hidden'])
hidden_layer_activation = tf.sigmoid(hidden_layer_calc)

# hidden layer to output layer operations
output_layer_calc       = tf.add(tf.matmul(hidden_layer_activation, W['output']), b['output'])
output_layer_activation = tf.sigmoid(output_layer_calc)

# mean squared error
error                   = tf.losses.mean_squared_error(yph, output_layer_activation)

# minimize error
optimizer               = tf.train.GradientDescentOptimizer(learning_rate = 0.3).minimize(error)

# 7 - RUN TENSORFLOW, TRAINING NEURAL NETWORK

In [21]:
init = tf.global_variables_initializer()

In [23]:
with tf.Session() as sess:
    sess.run(init)
    #print(sess.run(W['oculta']))
    #print(sess.run(W['saida']))
    #print(sess.run(b['oculta']))
    #print('\n')
    #print(sess.run(b['saida']))
    #print(sess.run(camada_oculta, feed_dict = {xph: X}))
    #print(sess.run(camada_oculta_ativacao, feed_dict = {xph: X}))
    #print(sess.run(camada_saida, feed_dict = {xph: X}))
    #print(sess.run(camada_saida_ativacao, feed_dict = {xph: X}))
    for epochs in range(10000):
        mean_error = 0
        _, cost = sess.run([optimizer, error], feed_dict = {xph: X, yph: y})
        if epochs % 200 == 0:
            #print(cost)
            mean_error += cost / 4
            print(mean_error)
    W_final, b_final = sess.run([W, b])
            

0.06465006619691849
0.061972007155418396
0.06102719530463219
0.05928775295615196
0.05635208263993263
0.05219634622335434
0.04727141931653023
0.04140934348106384
0.03413872420787811
0.02574206329882145
0.018057946115732193
0.012471776455640793
0.008845318108797073
0.006537177599966526
0.005031747743487358
0.004011303186416626
0.0032917524222284555
0.002765849232673645
0.0023693081457167864
0.0020622066222131252
0.0018188818357884884
0.0016222787089645863
0.0014607226476073265
0.0013260107953101397
0.0012122401967644691
0.001115074148401618
0.0010312602389603853
0.0009583269711583853
0.0008943575667217374
0.0008378529455512762
0.0007876235758885741
0.0007427131640724838
0.000702343531884253
0.0006658837664872408
0.0006328057497739792
0.0006026765331625938
0.0005751300486736
0.0005498561076819897
0.0005265934159979224
0.0005051158368587494
0.0004852325364481658
0.00046677771024405956
0.00044960490777157247
0.0004335902922321111
0.00041862131911329925
0.0004046039539389312
0.00039144983747

In [24]:
# Final Weights
W_final

{'hidden': array([[-6.1177316, -2.788611 , -4.6673865],
        [-5.275525 , -4.782033 ,  3.144581 ]], dtype=float32),
 'output': array([[-8.439485],
        [ 7.705766],
        [ 4.255086]], dtype=float32)}

In [25]:
# Final Bias weights
b_final

{'hidden': array([ 2.249805 ,  5.345482 , -2.0992012], dtype=float32),
 'output': array([-3.91807], dtype=float32)}

In [28]:
# test neural network
test_hidden_layer            = tf.add(tf.matmul(xph, W_final['hidden']), b_final['hidden'])
test_hidden_layer_activation = tf.sigmoid(test_hidden_layer)

test_output_layer            = tf.add(tf.matmul(test_hidden_layer_activation, W_final['output']), b_final['output'])
test_output_layer_activation = tf.sigmoid(test_output_layer)

In [29]:
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(camada_saida_ativacao_teste, feed_dict = {xph: X}))

[[0.03170761]
 [0.9770261 ]
 [0.9554363 ]
 [0.04492554]]
